### ISSUE TITLE
Problema con Toolbar al final de la ventana

### ISSUE THREAD

**Issue by jrsancheze** [ivanilmarcelino/designer#2]
No mantiene la configuración cuando deseo utilizar la barra de tareas al final de la ventana. Cada vez que modifico me configura para utilizar la barra de tareas en la parte de arriba de la ventana.

**Comment by ivanilmarcelino** [comment]
Você está usando a versão atualizado?
veja o vídeo abaixo que demonstra o uso de várias formas;
https://www.youtube.com/watch?v=TvRSPaPu8pw

**Comment by ivanilmarcelino** [comment]
Está correto;
Uma toolbar simples quando colocada embaixo não esta sendo mantida, apenas se usar mais de uma toolbar; esta sendo corrigido;

**Comment by ivanilmarcelino** [comment]
Correção disponível para download;
Grato.
